# Generate a full per-equation estimation-diagnostics table for MARTIN.
#
#   Rscript scripts/equation_diagnostics.R
#
# Estimates the frozen model (load_martin, 2019Q3 sample) and writes
# docs/equation_diagnostics.md: one row per behavioural equation with sample,
# coefficient counts, significance, fit (R2/adjR2), residual diagnostics
# (DW, SER), and a status flag. Re-run after any change to the model in extdata/model_af/.

root <- tryCatch(here::here(), error = function(e) getwd())
suppressWarnings(suppressMessages(source(file.path(root, "setup.R"))))

PIN <- 1e6  # |t| above this => the coefficient is pinned/restricted, not freely fit

db <- read_fixture()
model <- suppressWarnings(suppressMessages(
  load_martin(db, variant = "af", estimate = TRUE)))
cat <- tryCatch(equation_catalogue(), error = function(e) NULL)

eqs <- names(model$behaviorals)
num <- function(x) suppressWarnings(as.numeric(x))

rows <- lapply(eqs, function(eq) {
  b <- model$behaviorals[[eq]]; s <- b$statistics
  co <- num(b$coefficients)
  t  <- num(s$CoeffTstatistic); if (length(t) != length(co)) t <- rep(NA, length(co))
  pinned <- is.infinite(t) | (!is.na(t) & abs(t) > PIN)
  free   <- !pinned & !is.na(t)
  insig  <- free & abs(t) < 1.96
  tr <- num(s$TSRANGE)
  sample <- if (length(tr) == 4) sprintf("%dQ%d-%dQ%d", tr[1], tr[2], tr[3], tr[4]) else NA
  r2 <- num(s$RSquared); dw <- num(s$DurbinWatson)
  calibrated <- all(pinned | is.na(t))
  status <- if (calibrated) "calibrated" else "estimated"
  notes <- c(
    if (!calibrated && !is.na(r2) && r2 < 0.20) "weak-fit(R2<0.2)",
    if (!calibrated && sum(insig) > 0) sprintf("%d insig", sum(insig)),
    if (!calibrated && !is.na(dw) && dw < 1.5) "autocorr(DW<1.5)"
  )
  nm <- if (!is.null(cat)) cat$name[match(eq, cat$code)] else NA
  sec <- if (!is.null(cat)) cat$sector[match(eq, cat$code)] else NA
  data.frame(
    eq = eq, name = ifelse(is.na(nm), "", nm), sector = ifelse(is.na(sec), "", sec),
    sample = sample, n = num(s$ObservationsCount),
    ncoef = length(co), pinned = sum(pinned), free = sum(free), insig = sum(insig),
    R2 = round(r2, 3), adjR2 = round(num(s$AdjustedRSquared), 3),
    DW = round(dw, 2), SER = signif(num(s$StandardErrorRegression), 3),
    status = status, notes = paste(notes, collapse = "; "),
    stringsAsFactors = FALSE)
})
tab <- do.call(rbind, rows)

est <- tab[tab$status == "estimated", ]
cal <- tab[tab$status == "calibrated", ]
est <- est[order(-est$insig, est$R2), ]
cal <- cal[order(cal$eq), ]

md <- function(d) {
  hdr <- "| eq | name | sector | sample | n | coef | pinned | free | insig | R2 | adjR2 | DW | SER | notes |"
  sep <- "|---|---|---|---|--:|--:|--:|--:|--:|--:|--:|--:|--:|---|"
  body <- apply(d, 1, function(r) sprintf(
    "| `%s` | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |",
    r["eq"], r["name"], r["sector"], r["sample"], r["n"], r["ncoef"],
    r["pinned"], r["free"], r["insig"], r["R2"], r["adjR2"], r["DW"], r["SER"], r["notes"]))
  paste(c(hdr, sep, body), collapse = "\n")
}

out <- c(
  "# MARTIN per-equation estimation diagnostics",
  "",
  "Generated by `scripts/equation_diagnostics.R` against the frozen model",
  "(`load_martin`, embedded 2019Q3 estimation sample, bundled fixture).",
  "Re-run after any change to the model in `extdata/model_af/`.",
  "",
  "## Summary",
  "",
  sprintf("- Behavioural blocks: **%d** — **%d estimated**, **%d calibrated** (all coefficients pinned `c1=1` / restricted: rules, trends, accounting identities).",
          nrow(tab), nrow(est), nrow(cal)),
  sprintf("- Coefficients: **%d** total — **%d freely estimated**, **%d pinned**.",
          sum(tab$ncoef), sum(tab$free), sum(tab$pinned)),
  sprintf("- Insignificant free coefficients (|t|<1.96): **%d** (%.0f%% of free), across **%d** estimated equations.",
          sum(tab$insig), 100 * sum(tab$insig) / sum(tab$free), sum(est$insig > 0)),
  "",
  "Columns: `pinned` = coefficients fixed by a single-value restriction (reported t≈Inf);",
  "`free` = freely estimated; `insig` = free coefficients with |t|<1.96. For calibrated",
  "equations R2/DW are mechanical (near-deterministic fit) and not a quality signal.",
  "",
  "## Estimated equations (sorted by # insignificant coefficients, then fit)",
  "",
  md(est),
  "",
  "## Calibrated / identity equations (pinned — not freely estimated)",
  "",
  md(cal),
  ""
)
dir.create(file.path(root, "docs"), showWarnings = FALSE)
writeLines(out, file.path(root, "docs", "equation_diagnostics.md"))
cat("wrote docs/equation_diagnostics.md (",
    nrow(est), "estimated +", nrow(cal), "calibrated )\n")
