# Chop-and-recover backtest for the nowcast handover layer.
#
# Reproducible, self-contained, and committed. It reads the bundled MARTIN
# data fixture (the same xlsx the martin package vendors) DIRECTLY via
# readxl, so it does not need the martin package to be installed and does
# not touch the network. For each handover variable present in the fixture
# it:
#
#   1. chops the last H quarters off,
#   2. forecasts H quarters ahead with each of {bridge, arima, naive},
#   3. compares the central forecast against the held-out actuals.
#
# The metric is mean absolute percentage error (MAPE) across all held-out
# (variable, horizon) points, plus the share of points recovered within
# 5%. We report what the code actually yields on the fixture -- no
# fabricated headline numbers.
#
# Run from the repo root:
#   Rscript scripts/handover_backtest.R
#
# It writes scripts/output/handover_backtest.md with the real figures.

repo <- tryCatch(here::here(), error = function(e) getwd())
suppressWarnings(suppressMessages(source(file.path(repo, "setup.R"))))

fixture <- extdata_path("martin_data_fixture.xlsx")
stopifnot(file.exists(fixture))

# ---- Build a bimets-style database from the fixture ----------------------
suppressWarnings(suppressMessages({
  raw <- readxl::read_excel(fixture)
}))

col_to_quarterly_ts <- function(col) {
  v <- raw[[col]]
  idx <- which(!is.na(v))
  if (length(idx) == 0L) return(NULL)
  span <- min(idx):max(idx)
  if (anyNA(v[span])) return(NULL)  # skip series with interior holes
  d0 <- raw$Dates[min(idx)]
  yr <- as.integer(format(d0, "%Y"))
  mo <- as.integer(format(d0, "%m"))
  q  <- (mo - 1L) %/% 3L + 1L
  bimets::TIMESERIES(v[span], START = c(yr, q), FREQ = 4)
}

vars <- intersect(handover_variables(), names(raw))
db <- list()
for (v in vars) {
  ts <- col_to_quarterly_ts(v)
  if (!is.null(ts) && length(as.numeric(ts)) >= 16L) db[[v]] <- ts
}
vars <- names(db)

# ---- Chop-and-recover over the database ----------------------------------
H <- 2L  # Q+0 and Q+1

# Truncate each series by H quarters, remembering the held-out actuals.
held_out <- list()
truncated <- list()
for (v in vars) {
  full <- as.numeric(db[[v]])
  n <- length(full)
  held_out[[v]] <- full[(n - H + 1):n]
  tsp0 <- stats::tsp(db[[v]])
  yr <- floor(tsp0[1] + 1e-9)
  q  <- round((tsp0[1] - yr) * 4 + 1)
  truncated[[v]] <- bimets::TIMESERIES(full[1:(n - H)],
                                       START = c(yr, q), FREQ = 4)
}

methods <- c("bridge", "arima", "naive")

run_method <- function(method) {
  recs <- lapply(vars, function(v) {
    fc <- tryCatch(
      nowcast_handover(truncated, h = H, method = method, variables = v),
      error = function(e) NULL
    )
    if (is.null(fc) || nrow(fc) != H) return(NULL)
    actual <- held_out[[v]]
    central <- fc$central
    tibble(
      variable = v,
      horizon  = seq_len(H),
      actual   = actual,
      central  = central,
      abs_pct_err = abs(central - actual) / pmax(abs(actual), 1e-6)
    )
  })
  dplyr::bind_rows(recs)
}

results <- lapply(methods, run_method)
names(results) <- methods

summarise_method <- function(df, method) {
  tibble(
    method   = method,
    n_points = nrow(df),
    n_vars   = length(unique(df$variable)),
    mape_pct = 100 * mean(df$abs_pct_err),
    median_ape_pct = 100 * stats::median(df$abs_pct_err),
    within_5pct  = mean(df$abs_pct_err < 0.05),
    within_10pct = mean(df$abs_pct_err < 0.10)
  )
}

summary_tbl <- dplyr::bind_rows(
  Map(summarise_method, results, names(results))
)

print(as.data.frame(summary_tbl), digits = 4)

# ---- Write the markdown report -------------------------------------------
fmt_pct <- function(x) sprintf("%.1f%%", x)
fmt_share <- function(x) sprintf("%.0f%%", 100 * x)

md_path <- file.path(repo, "scripts", "output", "handover_backtest.md")
dir.create(dirname(md_path), showWarnings = FALSE, recursive = TRUE)

lines <- c(
  "# Nowcast handover backtest (chop-and-recover)",
  "",
  sprintf(paste0("Generated by ",
                 "`scripts/handover_backtest.R` on %s."),
          format(Sys.Date())),
  "",
  "## What this measures",
  "",
  paste0(
    "For every handover variable present in the bundled MARTIN data fixture ",
    "(`extdata/martin_data_fixture.xlsx`), the script ",
    "chops the last ", H, " quarters off, forecasts ", H, " quarters ahead ",
    "with each method, and compares the central forecast against the ",
    "held-out actuals. The fixture's history ends 2019Q3, so this is a ",
    "pre-COVID, in-sample-vintage recovery test, not an out-of-sample ",
    "real-time evaluation."
  ),
  "",
  sprintf("Variables evaluated: %d. Held-out points per method: up to %d.",
          length(vars), length(vars) * H),
  "",
  "## Headline numbers (real, reproduced from the fixture)",
  "",
  "| Method | Points | MAPE | Median APE | Within 5% | Within 10% |",
  "|---|---|---|---|---|---|"
)
for (i in seq_len(nrow(summary_tbl))) {
  r <- summary_tbl[i, ]
  lines <- c(lines, sprintf(
    "| %s | %d | %s | %s | %s | %s |",
    r$method, r$n_points, fmt_pct(r$mape_pct), fmt_pct(r$median_ape_pct),
    fmt_share(r$within_5pct), fmt_share(r$within_10pct)
  ))
}
lines <- c(
  lines,
  "",
  "## Caveats",
  "",
  paste0(
    "- This is a smoke-test-grade backtest on a single frozen fixture, not ",
    "a forecast-accuracy benchmark. The horizon is short (", H, " quarters) ",
    "and the sample is one pre-COVID end-point."
  ),
  paste0(
    "- The `bridge` method here is fable's constrained AR(1)+seasonal-AR(1) ",
    "ARIMA, not the monthly-indicator `bridge_monthly` (the fixture has no ",
    "monthly indicators)."
  ),
  "- Numbers are whatever the committed code yields on the committed ",
  "  fixture; re-running the script regenerates this file."
)

writeLines(lines, md_path)
cat("\nWrote ", md_path, "\n", sep = "")
